# Generated by Django 5.1.4 on 2024-12-08 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_invite_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('total_ram', models.IntegerField()),
                ('total_cpu', models.IntegerField()),
                ('total_gpu', models.IntegerField()),
                ('available_ram', models.IntegerField()),
                ('available_cpu', models.IntegerField()),
                ('available_gpu', models.IntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
    ]
