# Generated by Django 5.1.4 on 2024-12-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='invite_code',
            field=models.CharField(unique=True),
        ),
    ]
